title = "ANDREFFS"
baseURL = "https://andreffs.com"
languageCode = "en-us"
publishDir = "docs"
tags = ["tags"]
disqusShortname = "andreffs"
googleAnalytics = "UA-71884481-1"
enableGitInfo = true
enableRobotsTXT = true
rssLimit = 20

ignorefiles = [
  "content/blog/_draft/.*"
]
theme = ["hugo-debugprint"]

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[author]
  name = "André Silva"
  email = "andreffs18@gmail.com"

[params]
    # Site HEAD's configs
    description = "Hey, I'm André Silva, a Software Engineer from Lisbon, Portugal and this is my personal website."
    socialHandler = "andreffs18"

    # Tag cloud params
    enableTagCloud = true
    fontUnit = "em"
    largestFontSize = 2.5
    smallestFontSize = 1
