title = "ANDREFFS"
baseURL = "https://andreffs.com"
languageCode = "en-us"
publishDir = "docs"
tags = ["tags"]
disqusShortname = "andreffs"
googleAnalytics = "UA-71884481-1"
enableGitInfo = true
enableRobotsTXT = true

ignorefiles = [
  "content/blog/_draft/.*"
]
theme = ["hugo-debugprint"]

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
    enableTagCloud = true
    fontUnit = "em"
    largestFontSize = 2.5
    smallestFontSize = 1

[menu]
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  #[[menu.main]]
  #  identifier = "projects"
  #  name = "Projects"
  #  url = "/projects/"
  #  weight = 4

  #[[menu.main]]
  #  identifier = "talks"
  #  name = "Talks"
  #  url = "/talks/"
  #  weight = 5

  [[menu.social]]
    identifier = "github"
    title="github"
    url="https://github.com/andreffs18"
    post="fa fa-github"

  [[menu.social]]
    identifier = "twitter"
    title="twitter"
    url="https://twitter.com/andreffs18"
    post="fa fa-twitter"

  [[menu.social]]
    identifier="instagram"
    title="instagram"
    url="http://instagram.com/andreffs18"
    post="fa fa-instagram"

  [[menu.social]]
    identifier="facebook"
    title="facebook"
    url="https://www.facebook.com/andreffs18"
    post="fa fa-facebook"

  [[menu.social]]
    identifier="linkedin"
    title="linkedin"
    url="https://pt.linkedin.com/in/andreffs18"
    post="fa fa-linkedin"

  [[menu.social]]
    identifier="e-mail"
    title="e-mail"
    url="mailto:andreffs18@gmail.com"
    post="fa fa-envelope"
